name: Development

on: push

jobs:
  snyk-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SAST Analysis - Snyk
        uses: snyk/actions/node@master
        # continue-on-error: true # provisional
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
